#!/bin/sh
set -eu
case "${1:-}" in
    remove|deconfigure)
        printf '%s\n' 'Before removal, use NetShield > Remove filter configuration and verify network access.'
        /var/jb/usr/bin/uicache -u /var/jb/Applications/NetShield.app
        ;;
esac
